version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  pull-request-branch-name:
    separator: "-"
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: rollup
    versions:
    - 2.35.1
    - 2.38.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: release-it
    versions:
    - 14.2.2
