env:
  global:
    - CC_TEST_REPORTER_ID=5df0c45e1b9cd012ffcd16ad6a65b5ddb87f36fa3e335c43458de53641cacc45
language: node_js
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: npm run test
    - stage: check
      name: "Linting"
      script: npm run lint